<a href="https://colab.research.google.com/github/Elijah-4/PyTorch-Study/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
np1 = np.random.rand(3, 4)
np1

array([[5.06987968e-01, 9.82295268e-01, 4.94120347e-03, 3.78197494e-01],
       [8.82607815e-01, 1.27496218e-01, 6.71414314e-01, 1.93031914e-01],
       [8.25935638e-01, 2.66019834e-01, 3.60274248e-04, 3.15045208e-02]])

In [5]:
np1.dtype

dtype('float64')

In [11]:
tensor_2d = torch.randn(3, 4)
tensor_2d
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[5.0699e-01, 9.8230e-01, 4.9412e-03, 3.7820e-01],
        [8.8261e-01, 1.2750e-01, 6.7141e-01, 1.9303e-01],
        [8.2594e-01, 2.6602e-01, 3.6027e-04, 3.1505e-02]], dtype=torch.float64)