<a href="https://colab.research.google.com/github/Elijah-4/PyTorch-Study/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import torch
import numpy as np

In [24]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [25]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [26]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [28]:
# sub funciton
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [29]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [30]:
# mult func
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [31]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [32]:
# div long
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
# remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [34]:
# remainder long
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [35]:
# exponents
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [36]:
# exp longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [37]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [38]:
# reassignment with _
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [39]:
tensor_a

tensor([ 6,  8, 10, 12])